---
title: Implantación de aplicaciones web PHP
author: 
  - José Domingo Muñoz
institute: "IES Gonzalo Nazareno"
date: Septiembre 2022
output: 
  beamer_presentation:
    includes:
      in_header: 
        - "../include/header.tex"
    slide_level: 2
    #toc: true
    keep_tex:  true
    
classoption: "aspectratio=169"
---

# Introducción a PHP

## PHP

* PHP es un acrónimo recursivo. Significa **PHP Hypertext Preprocessor**.
* PHP es un lenguaje de programación de propósito general. Pero se ha generalizado su uso en el **desarrollo web**.
* PHP se puede ejecutar desde la línea de comando (**cli**).
* Normalmente el PHP nos lo encontramos embebido en el HTML.

	```php
	<!DOCTYPE html>
	<html>
	<body>
		<h1>My first PHP page</h1>
		<?php
			echo "Hello World!";
		?>
	...
	```

## PHP

* En el desarrollo web profesional se suelen usar frameworks PHP: Laraverl, Symfony, ...
* Actualmente la versión es la 8. Aunque en Debian Stable usaremos la 8.2.
* Podemos servir páginas web construidas de varias formas:
	* Con el servidor web **Apache2** y el módulo **libapache2-mod-php**. El servidor web sirve el contenido estático y el contenido dinámico generado por el PHP.
	* Con el servidor web **Apache2** y un servidor de aplicaciones, por ejemplo, **fpm-php**. El servidor web sirve el contenido estático y hace de **proxy inverso** para las peticiones PHP, es decir pasa a **fpm-php** las peticiones en las que hay que ejecutar el código PHP.
	* Con el servidor web **nginx** y un servidor de aplicaciones, por ejemplo, **fpm-php**. El servidor web sirve el contenido estático y hace de **proxy inverso** para las peticiones PHP.

## Servidor LAMP

El acrónimo **LAMP** se refiere a un entorno configurado en un servidor que nos posibilita servir aplicaciones web escritas en PHP.

* **L**inux, el sistema operativo;
* **A**pache, el servidor web;
* **M**ySQL, **M**ariaDB, el gestor de bases de datos;
* **P**HP el lenguajes de programación.

**LEMP**: Cambiamos apache2 por nginx.

## CMS desarrollado con PHP

Un **sistema de gestión de contenidos o CMS** (del inglés *content management system*) es un programa informático que permite crear un entorno de trabajo para la creación y administración de contenidos, principalmente en páginas web, por parte de los administradores, editores, participantes y demás usuarios.

* CMS genéricos (para cualquier tipo de sitio web): Drupal, Joomla,...
* CMS para blogs: Wordpress,...
* CMS para foros: FUDforum,...
* CMS para wikis: Wikimedia, ...
* CMS para e-learning (aprendizaje en línea): moodle, ...
* CMS para e-commerce (comercio electrónico): openCart, Prestashop
...

*  \color{blue}[Lista de CMS](https://www.opensourcecms.com/)\color{darkgray}

## Principales pasos para instalar un CMS PHP 

1. Crear la base de datos y el usuario de la base de datos que vamos a utilizar para que la aplicación acceda a los datos.
2. ¿Dónde vamos a implantar la aplicación? O en un virtual host o en un directorio dentro de un virtualhost.
    Por ejemplo, si instalo WordPress:

    * En un VirtualHost accederíamos con `wordpress.gonzalonazareno.org`, los ficheros del CMS estarían en la raíz del *DocumentRoot*.
    * En un directorio dentro de un VirtualHost, se accedería, por ejemplo, con `dit.gonzalonazareno.org/wordpress`, los ficheros del CMS estarían en el directorio `wordpress` dentro del *DocumentRoot*.
3. Descargar los ficheros del CMS y subirlos los ficheros del CMS al servidor. Varias formas: FTP, scp, wget, ...)
4. Acceso a la URL de instalación e iniciar el proceso de configuración.

## Principales pasos para instalar un CMS PHP 

5. Un punto importante en el proceso de configuración es indicar las credenciales para el acceso a la Base de Datos: hay que indicar el usuario y contraseña que vamos a utilizar, el nombre de la base de datos y la dirección donde se encuentra el servidor de base de datos. Si el servidor de BD está en la misma máquina que el servidor web se pondrá `localhost`, sino se pondrá la IP o el nombre del servidor.
6. En el proceso de configuración e instalación, quizás se nos pida instalar determinadas librerias de PHP.

## Principales pasos para instalar un CMS PHP 

7. Terminamos la configuración de la aplicación: Nombre, usuario administrador, ...
8. La información que introducimos para configurar la aplicación se puede guardar en un fichero o en la base de datos:
    * Las credenciales de conexión se suelen guardar en un fichero de configuración.
    * Las demás configuraciones se suelen guardar en la base de datos, pero esto varia según el CMS que estemos instalando.

## Vídeo: Como instalar Wordpress en un entorno LAMP

* \color{blue}[Vídeo: Como instalar Wordpress en un entorno LAMP](https://www.youtube.com/watch?v=muAKPiPqW6g)\color{darkgray}
